name: ESP-IDF CI

on:
  workflow_call:
    inputs:
      target_path:
        type: string
        description: 'Path value to select a specific target in the matrix'
        required: true
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - name: v51_build
            version_number: release-v5.1
            target: esp32c6
          - name: v52_build
            version_number: release-v5.2
            target: esp32c6
          - name: v53_build
            version_number: release-v5.3
            target: esp32c6
          - name: v54_build
            version_number: release-v5.4
            target: esp32c6
          - name: v55_build
            version_number: release-v5.5
            target: esp32c6
        path:
          - name: examples/espidf/integration
    steps:
      - if: github.event_name == 'workflow_call' && matrix.path.name != inputs.target_path
        run: exit 0

      - uses: actions/checkout@v4.1.1

      - name: ESP-IDF Build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: ${{ matrix.version.version_number }}
          target: ${{ matrix.version.target }}
          path: ${{ matrix.path.name }}
