name: PlatformIO CI

on:
  workflow_call:
    inputs:
      target_path:
        type: string
        description: 'Path value to select a specific target in the matrix'
        required: true
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - path: examples/espidf/integration/main/main.cpp

    steps:
      - if: github.event_name == 'workflow_call' && matrix.target.path != inputs.target_path
        run: exit 0

      - uses: actions/checkout@v4.1.1

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO targets
        run: ${{ env.PLATFORMIO_CI_BASE_CMD }}
        env:
          PLATFORMIO_CI_BASE_CMD: pio ci --lib="." --board=esp32-c6-devkitc-1 --project-option="build_unflags=-std=gnu++11" --project-option="build_flags=-std=gnu++17" --project-option="platform=espressif32@6.10.0" --project-option="lib_ldf_mode=deep"
          PLATFORMIO_CI_SRC: ${{ matrix.target.path }}
