name: Push ieee-802_15_4-network-shared to PlatformIO registry
on:
  release:
    types: [created]
jobs:
  build_examples_for_verification:
    uses: ./.github/workflows/platformio.yaml
    with:
      target_path: "examples/espidf/integration/main/main.cpp"

  upload_library:
    runs-on: ubuntu-latest
    needs: [build_examples_for_verification]
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Publish PlatformIO library
        run: pio pkg publish --owner johboh --no-notify --no-interactive
        env:
          PLATFORMIO_AUTH_TOKEN: ${{ secrets.PLATFORMIO_AUTH_TOKEN }}